name: fastLayersDecomposition
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - pillow
  - cvxopt
  - cython
  - websockets
  - pip
  - git
  - pip:
     - pyopencl
